### PR TITLE
Allow for manual addition of files in the db

### PR DESCRIPTION
**Pull request by OlivierBondu**
I don't have any recent crab task at hand, could someone check that it does not break `runPostCrab.py` ?

### CODE REVIEW

**Comment by blinkseb** [comment]
`runPostCrab.py` does not use this script, so no reason it breaks :)

**Comment by blinkseb** [comment]
If there's a lot of files, I'm afraid you'll hit the maximum command line size. Ideal way would be to read the files from a file (for example containing on each line one file).

**Comment by BrieucF** [comment]
(Olivier speaking) On the other hand here we would like to add this functionality to add only one file, so creating a file containing one line containing the path of one file is an other kind of overkill :p

**Comment by blinkseb** [comment]
Ahah indeed

**Pull request merged**
