### PR TITLE
Move SAMADhi.py and das_import.py to python/

### PR DESCRIPTION
**Pull request by pieterdavid**
This makes the package automatically installable with `scram`, such that there is no need for the `sys.path` manipulation in GridIn and CommonTools any more (and the part that is still needed for storm can be moved to `SAMADhi.py` instead of being copied everywhere).
The only flexibility that is lost is installing outside a CMSSW project (but the workaround was assuming this to be in $CMSSW_BASE/src/cp3_llbb/SAMADhi` already anyway) - let me know if there is something else that I overlooked.

I have only tested a SAMADhi search with this... so we should at least wait for more testing, and for the corresponding GridIn and CommonTools changes to be ready as well, before considering to merge this.

### CODE REVIEW

**Comment by swertz** [comment]
Thanks, much cleaner indeed in the other packages!

I can't see any obvious problem, but I'll let others check before merging...

**Comment by blinkseb** [comment]
This is the correct way to do things IMO, thanks a lot! 👍

**Comment by OlivierBondu** [comment]
thanks a lot! looks better indeed! maybe let's wait for a real-use confirmation this doesn't break anything before merging ? (though I don't expect any problem...)

**Comment by OlivierBondu** [comment]
ok, merging this :) we'll do a real-conditions testing for the ZA prod !

**Pull request merged**
