### PR TITLE
Add a dashboard with database statistics and curation data

### PR DESCRIPTION
**Pull request by delaere**
This PR adds dashboard functionalities to the SAMADhi interface.
Dashboard 'actions' are added for each table, and point to dedicated pages where data from json files produced by the db analysis script are displayed.

### CODE REVIEW

**Comment by delaere** [comment]
I was expecting the comment... I will see what I can do since this is something that I did long ago. Making the installation more complicated may make the deployment on server02 more tricky (even if I hope that docker is an option, this has to be discussed with Jérôme).

**Comment by delaere** [comment]
I managed to simplify the installation procedure for packages that we depend on. There is one script to run to install bootstrap and highcharts. I also modified the Dockerfile to install build tools and standard libraries (+ running the script). So, it still works out of the box in docker, and the script should suffice on a well configured server. Only drawback: the compilation takes ~20 minutes.

**Comment by pieterdavid** [comment]
Nice! (detail: I don't know how big two ~175k lines patches are in git, but you may save them from the repo size by squashing the first and last commit into one, e.g. with `git rebase -i`)
For the 20min compilation for the docker image I don't know, but it doesn't sound excessive to me. Maybe Jérôme can give his opinion on that part? (I'd 'mention' him, but I don't immediately find him on github)

**Comment by delaere** [comment]
I was thinking about squashing the commits indeed, but I would have to merge them all. I can do it... the net gain would be ~20MB uncompressed. Not sure that it is worth for such a small project.

**Comment by pieterdavid** [comment]
I think it's worth it if it doesn't take much time... if the big "add" and "remove" commits are independent of the rest it should be safe to reorder and squash those two, I quickly tried `git rebase -i master` and then
```
pick d9332da add dashboard actions
squash e3a3a52 slim down the dashboard source
pick 3e57e22 adapt to the go das client
pick b66e7bf extend the analysis code to the analysis table
pick 678d815 dashboard page for analyses
pick c36bd4a small precaution and make-up for pie charts
```
which seems to work fine.

**Comment by delaere** [comment]
ok, here we go. Thanks!

**Pull request merged**
